.grammar_size = (int[])
{
    1, 3, 1, 3, 1, 1, 3, 
},
.grammar_left = (int[])
{
    1, 2, 2, 4, 4, 6, 6, 
},
.token_list = 
{
    .size = 10,
    .list = (token_t[])
    {
        {
            .type = "$",
            .data = "",
        },
        {
            .type = "^",
            .data = "",
        },
        {
            .type = "E",
            .data = "",
        },
        {
            .type = "OP",
            .data = "+",
        },
        {
            .type = "T",
            .data = "",
        },
        {
            .type = "OP",
            .data = "*",
        },
        {
            .type = "F",
            .data = "",
        },
        {
            .type = "DIG",
            .data = "",
        },
        {
            .type = "LP",
            .data = "",
        },
        {
            .type = "RP",
            .data = "",
        },
    },
},
.trans = (table_cell_t*[])
{
    (table_cell_t[])
    {
        {AC_ERROR, 0},
        {AC_ERROR, 0},
        {AC_SHIFT, 1},
        {AC_ERROR, 0},
        {AC_SHIFT, 2},
        {AC_ERROR, 0},
        {AC_SHIFT, 3},
        {AC_SHIFT, 4},
        {AC_SHIFT, 5},
        {AC_ERROR, 0},
    },
    (table_cell_t[])
    {
        {AC_ACCEPT, 0},
        {AC_ERROR, 0},
        {AC_ERROR, 0},
        {AC_SHIFT, 6},
        {AC_ERROR, 0},
        {AC_ERROR, 0},
        {AC_ERROR, 0},
        {AC_ERROR, 0},
        {AC_ERROR, 0},
        {AC_ERROR, 0},
    },
    (table_cell_t[])
    {
        {AC_REDUCE, 2},
        {AC_ERROR, 0},
        {AC_ERROR, 0},
        {AC_REDUCE, 2},
        {AC_ERROR, 0},
        {AC_SHIFT, 7},
        {AC_ERROR, 0},
        {AC_ERROR, 0},
        {AC_ERROR, 0},
        {AC_ERROR, 0},
    },
    (table_cell_t[])
    {
        {AC_REDUCE, 4},
        {AC_ERROR, 0},
        {AC_ERROR, 0},
        {AC_REDUCE, 4},
        {AC_ERROR, 0},
        {AC_REDUCE, 4},
        {AC_ERROR, 0},
        {AC_ERROR, 0},
        {AC_ERROR, 0},
        {AC_ERROR, 0},
    },
    (table_cell_t[])
    {
        {AC_REDUCE, 5},
        {AC_ERROR, 0},
        {AC_ERROR, 0},
        {AC_REDUCE, 5},
        {AC_ERROR, 0},
        {AC_REDUCE, 5},
        {AC_ERROR, 0},
        {AC_ERROR, 0},
        {AC_ERROR, 0},
        {AC_ERROR, 0},
    },
    (table_cell_t[])
    {
        {AC_ERROR, 0},
        {AC_ERROR, 0},
        {AC_SHIFT, 8},
        {AC_ERROR, 0},
        {AC_SHIFT, 9},
        {AC_ERROR, 0},
        {AC_SHIFT, 10},
        {AC_SHIFT, 11},
        {AC_SHIFT, 12},
        {AC_ERROR, 0},
    },
    (table_cell_t[])
    {
        {AC_ERROR, 0},
        {AC_ERROR, 0},
        {AC_ERROR, 0},
        {AC_ERROR, 0},
        {AC_SHIFT, 13},
        {AC_ERROR, 0},
        {AC_SHIFT, 3},
        {AC_SHIFT, 4},
        {AC_SHIFT, 5},
        {AC_ERROR, 0},
    },
    (table_cell_t[])
    {
        {AC_ERROR, 0},
        {AC_ERROR, 0},
        {AC_ERROR, 0},
        {AC_ERROR, 0},
        {AC_ERROR, 0},
        {AC_ERROR, 0},
        {AC_SHIFT, 14},
        {AC_SHIFT, 4},
        {AC_SHIFT, 5},
        {AC_ERROR, 0},
    },
    (table_cell_t[])
    {
        {AC_ERROR, 0},
        {AC_ERROR, 0},
        {AC_ERROR, 0},
        {AC_SHIFT, 15},
        {AC_ERROR, 0},
        {AC_ERROR, 0},
        {AC_ERROR, 0},
        {AC_ERROR, 0},
        {AC_ERROR, 0},
        {AC_SHIFT, 16},
    },
    (table_cell_t[])
    {
        {AC_ERROR, 0},
        {AC_ERROR, 0},
        {AC_ERROR, 0},
        {AC_REDUCE, 2},
        {AC_ERROR, 0},
        {AC_SHIFT, 17},
        {AC_ERROR, 0},
        {AC_ERROR, 0},
        {AC_ERROR, 0},
        {AC_REDUCE, 2},
    },
    (table_cell_t[])
    {
        {AC_ERROR, 0},
        {AC_ERROR, 0},
        {AC_ERROR, 0},
        {AC_REDUCE, 4},
        {AC_ERROR, 0},
        {AC_REDUCE, 4},
        {AC_ERROR, 0},
        {AC_ERROR, 0},
        {AC_ERROR, 0},
        {AC_REDUCE, 4},
    },
    (table_cell_t[])
    {
        {AC_ERROR, 0},
        {AC_ERROR, 0},
        {AC_ERROR, 0},
        {AC_REDUCE, 5},
        {AC_ERROR, 0},
        {AC_REDUCE, 5},
        {AC_ERROR, 0},
        {AC_ERROR, 0},
        {AC_ERROR, 0},
        {AC_REDUCE, 5},
    },
    (table_cell_t[])
    {
        {AC_ERROR, 0},
        {AC_ERROR, 0},
        {AC_SHIFT, 18},
        {AC_ERROR, 0},
        {AC_SHIFT, 9},
        {AC_ERROR, 0},
        {AC_SHIFT, 10},
        {AC_SHIFT, 11},
        {AC_SHIFT, 12},
        {AC_ERROR, 0},
    },
    (table_cell_t[])
    {
        {AC_REDUCE, 1},
        {AC_ERROR, 0},
        {AC_ERROR, 0},
        {AC_REDUCE, 1},
        {AC_ERROR, 0},
        {AC_SHIFT, 7},
        {AC_ERROR, 0},
        {AC_ERROR, 0},
        {AC_ERROR, 0},
        {AC_ERROR, 0},
    },
    (table_cell_t[])
    {
        {AC_REDUCE, 3},
        {AC_ERROR, 0},
        {AC_ERROR, 0},
        {AC_REDUCE, 3},
        {AC_ERROR, 0},
        {AC_REDUCE, 3},
        {AC_ERROR, 0},
        {AC_ERROR, 0},
        {AC_ERROR, 0},
        {AC_ERROR, 0},
    },
    (table_cell_t[])
    {
        {AC_ERROR, 0},
        {AC_ERROR, 0},
        {AC_ERROR, 0},
        {AC_ERROR, 0},
        {AC_SHIFT, 19},
        {AC_ERROR, 0},
        {AC_SHIFT, 10},
        {AC_SHIFT, 11},
        {AC_SHIFT, 12},
        {AC_ERROR, 0},
    },
    (table_cell_t[])
    {
        {AC_REDUCE, 6},
        {AC_ERROR, 0},
        {AC_ERROR, 0},
        {AC_REDUCE, 6},
        {AC_ERROR, 0},
        {AC_REDUCE, 6},
        {AC_ERROR, 0},
        {AC_ERROR, 0},
        {AC_ERROR, 0},
        {AC_ERROR, 0},
    },
    (table_cell_t[])
    {
        {AC_ERROR, 0},
        {AC_ERROR, 0},
        {AC_ERROR, 0},
        {AC_ERROR, 0},
        {AC_ERROR, 0},
        {AC_ERROR, 0},
        {AC_SHIFT, 20},
        {AC_SHIFT, 11},
        {AC_SHIFT, 12},
        {AC_ERROR, 0},
    },
    (table_cell_t[])
    {
        {AC_ERROR, 0},
        {AC_ERROR, 0},
        {AC_ERROR, 0},
        {AC_SHIFT, 15},
        {AC_ERROR, 0},
        {AC_ERROR, 0},
        {AC_ERROR, 0},
        {AC_ERROR, 0},
        {AC_ERROR, 0},
        {AC_SHIFT, 21},
    },
    (table_cell_t[])
    {
        {AC_ERROR, 0},
        {AC_ERROR, 0},
        {AC_ERROR, 0},
        {AC_REDUCE, 1},
        {AC_ERROR, 0},
        {AC_SHIFT, 17},
        {AC_ERROR, 0},
        {AC_ERROR, 0},
        {AC_ERROR, 0},
        {AC_REDUCE, 1},
    },
    (table_cell_t[])
    {
        {AC_ERROR, 0},
        {AC_ERROR, 0},
        {AC_ERROR, 0},
        {AC_REDUCE, 3},
        {AC_ERROR, 0},
        {AC_REDUCE, 3},
        {AC_ERROR, 0},
        {AC_ERROR, 0},
        {AC_ERROR, 0},
        {AC_REDUCE, 3},
    },
    (table_cell_t[])
    {
        {AC_ERROR, 0},
        {AC_ERROR, 0},
        {AC_ERROR, 0},
        {AC_REDUCE, 6},
        {AC_ERROR, 0},
        {AC_REDUCE, 6},
        {AC_ERROR, 0},
        {AC_ERROR, 0},
        {AC_ERROR, 0},
        {AC_REDUCE, 6},
    },
},
